import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'
import Navbar from './components/Navbar'
import ParticleBackground from './components/ParticlesBackground'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Gelo Portfolio',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <>
                <Head>
                    <title>{metadata.title}</title>
                    <meta name="description" content={metadata.description} />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <body className={inter.className}>
                    <Navbar />
                    {children}
                </body>
            </>
        </html>
    )
}
